apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
  namespace: ecommerce
data:
  PORT: "8001"
  MONGO_HOST: "customer-db"
  MONGO_PORT: "27017"
  DB_NAME: "msytt_customer"
  EXCHANGE_NAME: "ONLINE_STORE"
  MSG_QUEUE_URL: "amqp://rabbitmq:5672"
  NODE_ENV: "prod"
