sonar.projectKey=TA-rathnayaka_ecommerce-microservice
sonar.organization=TA-rathnayaka

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Ecommerce Microservice
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/coverage/**,azure/**,k8s/**

# Define modules/sub-projects for better visibility
sonar.modules=backend-customer,backend-products,backend-shopping,frontend

backend-customer.sonar.projectName=Customer Service
backend-customer.sonar.sources=backend/customer/src

backend-products.sonar.projectName=Products Service
backend-products.sonar.sources=backend/products/src

backend-shopping.sonar.projectName=Shopping Service
backend-shopping.sonar.sources=backend/shopping/src

frontend.sonar.projectName=Frontend App
frontend.sonar.sources=frontend/src
