worker_processes 1;

events { worker_connections 1024; }

http {

    # Upstream definitions for Azure Container Apps internal DNS
    upstream products_upstream {
        server ${PRODUCTS_HOST}:8002;
    }

    upstream shopping_upstream {
        server ${SHOPPING_HOST}:8003;
    }

    upstream customer_upstream {
        server ${CUSTOMER_HOST}:8001;
    }

    server {

        listen 8000;
        charset utf-8;

        location / {
            proxy_pass http://products_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Content-Type $http_content_type;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_request_body on;
            proxy_cache_bypass $http_upgrade;
        }

        location ~ ^/shopping {
            rewrite ^/shopping/(.*) /$1 break;
            proxy_pass http://shopping_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Content-Type $http_content_type;
            proxy_set_header Content-Length $content_length;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_request_body on;
            proxy_cache_bypass $http_upgrade;
        }
        location /customer {
            rewrite ^/customer/(.*)$ /$1 break;
            proxy_pass http://customer_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Content-Type $http_content_type;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_request_body on;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
