apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
  namespace: ecommerce
data:
  PORT: "8002"
  MONGO_HOST: "products-db"
  MONGO_PORT: "27017"
  DB_NAME: "msytt_product"
  EXCHANGE_NAME: "ONLINE_STORE"
  MSG_QUEUE_URL: "amqp://rabbitmq:5672"
  NODE_ENV: "prod"
