apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deploy
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: products
          image: tharanga123acr.azurecr.io/tharanga123acr.azurecr.io/tharanga123acr.azurecr.io/tharanga123acr.azurecr.io/tharanga123acr.azurecr.io/ecommerce/products:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: MONGO_PASS
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: APP_SECRET
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: products-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: products-config
                  key: MONGO_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: products-config
                  key: DB_NAME
            - name: MONGODB_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@$(MONGO_HOST):$(MONGO_PORT)/$(DB_NAME)?authSource=admin"
          envFrom:
            - configMapRef:
                name: products-config
